// All 114 Surahs with their metadata
export const SURAHS = [
  { number: 1, name: 'Al-Fatihah', nameArabic: 'الفاتحة', transliteration: 'The Opener', verses: 7 },
  { number: 2, name: 'Al-Baqarah', nameArabic: 'البقرة', transliteration: 'The Cow', verses: 286 },
  { number: 3, name: 'Ali \'Imran', nameArabic: 'آل عمران', transliteration: 'Family of Imran', verses: 200 },
  { number: 4, name: 'An-Nisa', nameArabic: 'النساء', transliteration: 'The Women', verses: 176 },
  { number: 5, name: 'Al-Ma\'idah', nameArabic: 'المائدة', transliteration: 'The Table Spread', verses: 120 },
  { number: 6, name: 'Al-An\'am', nameArabic: 'الأنعام', transliteration: 'The Cattle', verses: 165 },
  { number: 7, name: 'Al-A\'raf', nameArabic: 'الأعراف', transliteration: 'The Heights', verses: 206 },
  { number: 8, name: 'Al-Anfal', nameArabic: 'الأنفال', transliteration: 'The Spoils of War', verses: 75 },
  { number: 9, name: 'At-Tawbah', nameArabic: 'التوبة', transliteration: 'The Repentance', verses: 129 },
  { number: 10, name: 'Yunus', nameArabic: 'يونس', transliteration: 'Jonah', verses: 109 },
  { number: 11, name: 'Hud', nameArabic: 'هود', transliteration: 'Hud', verses: 123 },
  { number: 12, name: 'Yusuf', nameArabic: 'يوسف', transliteration: 'Joseph', verses: 111 },
  { number: 13, name: 'Ar-Ra\'d', nameArabic: 'الرعد', transliteration: 'The Thunder', verses: 43 },
  { number: 14, name: 'Ibrahim', nameArabic: 'إبراهيم', transliteration: 'Abraham', verses: 52 },
  { number: 15, name: 'Al-Hijr', nameArabic: 'الحجر', transliteration: 'The Rocky Tract', verses: 99 },
  { number: 16, name: 'An-Nahl', nameArabic: 'النحل', transliteration: 'The Bee', verses: 128 },
  { number: 17, name: 'Al-Isra', nameArabic: 'الإسراء', transliteration: 'The Night Journey', verses: 111 },
  { number: 18, name: 'Al-Kahf', nameArabic: 'الكهف', transliteration: 'The Cave', verses: 110 },
  { number: 19, name: 'Maryam', nameArabic: 'مريم', transliteration: 'Mary', verses: 98 },
  { number: 20, name: 'Taha', nameArabic: 'طه', transliteration: 'Ta-Ha', verses: 135 },
  { number: 21, name: 'Al-Anbya', nameArabic: 'الأنبياء', transliteration: 'The Prophets', verses: 112 },
  { number: 22, name: 'Al-Hajj', nameArabic: 'الحج', transliteration: 'The Pilgrimage', verses: 78 },
  { number: 23, name: 'Al-Mu\'minun', nameArabic: 'المؤمنون', transliteration: 'The Believers', verses: 118 },
  { number: 24, name: 'An-Nur', nameArabic: 'النور', transliteration: 'The Light', verses: 64 },
  { number: 25, name: 'Al-Furqan', nameArabic: 'الفرقان', transliteration: 'The Criterion', verses: 77 },
  { number: 26, name: 'Ash-Shu\'ara', nameArabic: 'الشعراء', transliteration: 'The Poets', verses: 227 },
  { number: 27, name: 'An-Naml', nameArabic: 'النمل', transliteration: 'The Ant', verses: 93 },
  { number: 28, name: 'Al-Qasas', nameArabic: 'القصص', transliteration: 'The Stories', verses: 88 },
  { number: 29, name: 'Al-\'Ankabut', nameArabic: 'العنكبوت', transliteration: 'The Spider', verses: 69 },
  { number: 30, name: 'Ar-Rum', nameArabic: 'الروم', transliteration: 'The Romans', verses: 60 },
  { number: 31, name: 'Luqman', nameArabic: 'لقمان', transliteration: 'Luqman', verses: 34 },
  { number: 32, name: 'As-Sajdah', nameArabic: 'السجدة', transliteration: 'The Prostration', verses: 30 },
  { number: 33, name: 'Al-Ahzab', nameArabic: 'الأحزاب', transliteration: 'The Combined Forces', verses: 73 },
  { number: 34, name: 'Saba', nameArabic: 'سبأ', transliteration: 'Sheba', verses: 54 },
  { number: 35, name: 'Fatir', nameArabic: 'فاطر', transliteration: 'Originator', verses: 45 },
  { number: 36, name: 'Ya-Sin', nameArabic: 'يس', transliteration: 'Ya Sin', verses: 83 },
  { number: 37, name: 'As-Saffat', nameArabic: 'الصافات', transliteration: 'Those who set the Ranks', verses: 182 },
  { number: 38, name: 'Sad', nameArabic: 'ص', transliteration: 'The Letter Saad', verses: 88 },
  { number: 39, name: 'Az-Zumar', nameArabic: 'الزمر', transliteration: 'The Troops', verses: 75 },
  { number: 40, name: 'Ghafir', nameArabic: 'غافر', transliteration: 'The Forgiver', verses: 85 },
  { number: 41, name: 'Fussilat', nameArabic: 'فصلت', transliteration: 'Explained in Detail', verses: 54 },
  { number: 42, name: 'Ash-Shuraa', nameArabic: 'الشورى', transliteration: 'The Consultation', verses: 53 },
  { number: 43, name: 'Az-Zukhruf', nameArabic: 'الزخرف', transliteration: 'The Ornaments of Gold', verses: 89 },
  { number: 44, name: 'Ad-Dukhan', nameArabic: 'الدخان', transliteration: 'The Smoke', verses: 59 },
  { number: 45, name: 'Al-Jathiyah', nameArabic: 'الجاثية', transliteration: 'The Crouching', verses: 37 },
  { number: 46, name: 'Al-Ahqaf', nameArabic: 'الأحقاف', transliteration: 'The Wind-Curved Sandhills', verses: 35 },
  { number: 47, name: 'Muhammad', nameArabic: 'محمد', transliteration: 'Muhammad', verses: 38 },
  { number: 48, name: 'Al-Fath', nameArabic: 'الفتح', transliteration: 'The Victory', verses: 29 },
  { number: 49, name: 'Al-Hujurat', nameArabic: 'الحجرات', transliteration: 'The Rooms', verses: 18 },
  { number: 50, name: 'Qaf', nameArabic: 'ق', transliteration: 'The Letter Qaf', verses: 45 },
  { number: 51, name: 'Adh-Dhariyat', nameArabic: 'الذاريات', transliteration: 'The Winnowing Winds', verses: 60 },
  { number: 52, name: 'At-Tur', nameArabic: 'الطور', transliteration: 'The Mount', verses: 49 },
  { number: 53, name: 'An-Najm', nameArabic: 'النجم', transliteration: 'The Star', verses: 62 },
  { number: 54, name: 'Al-Qamar', nameArabic: 'القمر', transliteration: 'The Moon', verses: 55 },
  { number: 55, name: 'Ar-Rahman', nameArabic: 'الرحمن', transliteration: 'The Beneficent', verses: 78 },
  { number: 56, name: 'Al-Waqi\'ah', nameArabic: 'الواقعة', transliteration: 'The Inevitable', verses: 96 },
  { number: 57, name: 'Al-Hadid', nameArabic: 'الحديد', transliteration: 'The Iron', verses: 29 },
  { number: 58, name: 'Al-Mujadila', nameArabic: 'المجادلة', transliteration: 'The Pleading Woman', verses: 22 },
  { number: 59, name: 'Al-Hashr', nameArabic: 'الحشر', transliteration: 'The Exile', verses: 24 },
  { number: 60, name: 'Al-Mumtahanah', nameArabic: 'الممتحنة', transliteration: 'She that is to be examined', verses: 13 },
  { number: 61, name: 'As-Saf', nameArabic: 'الصف', transliteration: 'The Ranks', verses: 14 },
  { number: 62, name: 'Al-Jumu\'ah', nameArabic: 'الجمعة', transliteration: 'The Congregation', verses: 11 },
  { number: 63, name: 'Al-Munafiqun', nameArabic: 'المنافقون', transliteration: 'The Hypocrites', verses: 11 },
  { number: 64, name: 'At-Taghabun', nameArabic: 'التغابن', transliteration: 'The Mutual Disillusion', verses: 18 },
  { number: 65, name: 'At-Talaq', nameArabic: 'الطلاق', transliteration: 'The Divorce', verses: 12 },
  { number: 66, name: 'At-Tahrim', nameArabic: 'التحريم', transliteration: 'The Prohibition', verses: 12 },
  { number: 67, name: 'Al-Mulk', nameArabic: 'الملك', transliteration: 'The Sovereignty', verses: 30 },
  { number: 68, name: 'Al-Qalam', nameArabic: 'القلم', transliteration: 'The Pen', verses: 52 },
  { number: 69, name: 'Al-Haqqah', nameArabic: 'الحاقة', transliteration: 'The Reality', verses: 52 },
  { number: 70, name: 'Al-Ma\'arij', nameArabic: 'المعارج', transliteration: 'The Ascending Stairways', verses: 44 },
  { number: 71, name: 'Nuh', nameArabic: 'نوح', transliteration: 'Noah', verses: 28 },
  { number: 72, name: 'Al-Jinn', nameArabic: 'الجن', transliteration: 'The Jinn', verses: 28 },
  { number: 73, name: 'Al-Muzzammil', nameArabic: 'المزمل', transliteration: 'The Enshrouded One', verses: 20 },
  { number: 74, name: 'Al-Muddaththir', nameArabic: 'المدثر', transliteration: 'The Cloaked One', verses: 56 },
  { number: 75, name: 'Al-Qiyamah', nameArabic: 'القيامة', transliteration: 'The Resurrection', verses: 40 },
  { number: 76, name: 'Al-Insan', nameArabic: 'الإنسان', transliteration: 'The Man', verses: 31 },
  { number: 77, name: 'Al-Mursalat', nameArabic: 'المرسلات', transliteration: 'The Emissaries', verses: 50 },
  { number: 78, name: 'An-Naba', nameArabic: 'النبأ', transliteration: 'The Tidings', verses: 40 },
  { number: 79, name: 'An-Nazi\'at', nameArabic: 'النازعات', transliteration: 'Those who drag forth', verses: 46 },
  { number: 80, name: 'Abasa', nameArabic: 'عبس', transliteration: 'He Frowned', verses: 42 },
  { number: 81, name: 'At-Takwir', nameArabic: 'التكوير', transliteration: 'The Overthrowing', verses: 29 },
  { number: 82, name: 'Al-Infitar', nameArabic: 'الانفطار', transliteration: 'The Cleaving', verses: 19 },
  { number: 83, name: 'Al-Mutaffifin', nameArabic: 'المطففين', transliteration: 'The Defrauding', verses: 36 },
  { number: 84, name: 'Al-Inshiqaq', nameArabic: 'الانشقاق', transliteration: 'The Sundering', verses: 25 },
  { number: 85, name: 'Al-Buruj', nameArabic: 'البروج', transliteration: 'The Mansions of the Stars', verses: 22 },
  { number: 86, name: 'At-Tariq', nameArabic: 'الطارق', transliteration: 'The Nightcomer', verses: 17 },
  { number: 87, name: 'Al-A\'la', nameArabic: 'الأعلى', transliteration: 'The Most High', verses: 19 },
  { number: 88, name: 'Al-Ghashiyah', nameArabic: 'الغاشية', transliteration: 'The Overwhelming', verses: 26 },
  { number: 89, name: 'Al-Fajr', nameArabic: 'الفجر', transliteration: 'The Dawn', verses: 30 },
  { number: 90, name: 'Al-Balad', nameArabic: 'البلد', transliteration: 'The City', verses: 20 },
  { number: 91, name: 'Ash-Shams', nameArabic: 'الشمس', transliteration: 'The Sun', verses: 15 },
  { number: 92, name: 'Al-Layl', nameArabic: 'الليل', transliteration: 'The Night', verses: 21 },
  { number: 93, name: 'Ad-Duhaa', nameArabic: 'الضحى', transliteration: 'The Morning Hours', verses: 11 },
  { number: 94, name: 'Ash-Sharh', nameArabic: 'الشرح', transliteration: 'The Relief', verses: 8 },
  { number: 95, name: 'At-Tin', nameArabic: 'التين', transliteration: 'The Fig', verses: 8 },
  { number: 96, name: 'Al-Alaq', nameArabic: 'العلق', transliteration: 'The Clot', verses: 19 },
  { number: 97, name: 'Al-Qadr', nameArabic: 'القدر', transliteration: 'The Power', verses: 5 },
  { number: 98, name: 'Al-Bayyinah', nameArabic: 'البينة', transliteration: 'The Clear Proof', verses: 8 },
  { number: 99, name: 'Az-Zalzalah', nameArabic: 'الزلزلة', transliteration: 'The Earthquake', verses: 8 },
  { number: 100, name: 'Al-Adiyat', nameArabic: 'العاديات', transliteration: 'The Courser', verses: 11 },
  { number: 101, name: 'Al-Qari\'ah', nameArabic: 'القارعة', transliteration: 'The Calamity', verses: 11 },
  { number: 102, name: 'At-Takathur', nameArabic: 'التكاثر', transliteration: 'The Rivalry in world increase', verses: 8 },
  { number: 103, name: 'Al-Asr', nameArabic: 'العصر', transliteration: 'The Declining Day', verses: 3 },
  { number: 104, name: 'Al-Humazah', nameArabic: 'الهمزة', transliteration: 'The Traducer', verses: 9 },
  { number: 105, name: 'Al-Fil', nameArabic: 'الفيل', transliteration: 'The Elephant', verses: 5 },
  { number: 106, name: 'Quraysh', nameArabic: 'قريش', transliteration: 'Quraysh', verses: 4 },
  { number: 107, name: 'Al-Ma\'un', nameArabic: 'الماعون', transliteration: 'The Small kindnesses', verses: 7 },
  { number: 108, name: 'Al-Kawthar', nameArabic: 'الكوثر', transliteration: 'The Abundance', verses: 3 },
  { number: 109, name: 'Al-Kafirun', nameArabic: 'الكافرون', transliteration: 'The Disbelievers', verses: 6 },
  { number: 110, name: 'An-Nasr', nameArabic: 'النصر', transliteration: 'The Divine Support', verses: 3 },
  { number: 111, name: 'Al-Masad', nameArabic: 'المسد', transliteration: 'The Palm Fiber', verses: 5 },
  { number: 112, name: 'Al-Ikhlas', nameArabic: 'الإخلاص', transliteration: 'The Sincerity', verses: 4 },
  { number: 113, name: 'Al-Falaq', nameArabic: 'الفلق', transliteration: 'The Daybreak', verses: 5 },
  { number: 114, name: 'An-Nas', nameArabic: 'الناس', transliteration: 'Mankind', verses: 6 }
];

export const getSurahByNumber = (number: number) => {
  return SURAHS.find(s => s.number === number);
};

// Helper function to get surah name based on language
export const getSurahName = (number: number, language: 'ar' | 'en' = 'en'): string => {
  const surah = getSurahByNumber(number);
  if (!surah) return '';
  return language === 'ar' ? surah.nameArabic : surah.name;
};
